name: Display Graphs in README
on:
  workflow_dispatch:

jobs:
  Create_Graph:
    runs-on: ubuntu-latest
    permissions:
      issues: read
    steps:
      - name: Check out repo content
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }} #gets the current repo
          ref: ${{ github.ref }} #main branch
          token: ${{ secrets.ORG_EF_TOKEN }}

      - name: debug
        run: |
          echo "Current Branch: ${{ github.ref }}"
          echo "Current Repo: ${{ github.repository }}"

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pandas
          pip install matplotlib
          pip install numpy

      - name: Execute script #outputs graph in graphs directory
        run: |
          python3 main.py
      
      - name: Debug
        run: |
          ls graphs
      
      - name: Commit and Push Changes
        run: |
          git config --global user.name ${{ secrets.NAME }}
          git config --global user.email ${{ secrets.EMAIL }}
          git add graphs/pr_duration_plot.png
          git commit -m "Add generated graph"
          git push origin main