name: Display Graphs in README
on: [workflow_dispatch, push]

jobs:
  Create_Graph:
    runs-on: ubuntu-latest
    permissions:
      issues: read
    steps:
      - name: Check out repo content
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }} #gets the current repo
          ref: ${{ github.ref }} #gets the current branch
          token: ${{ secrets.ORG_EF_TOKEN }}

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        run: |
          python3 -m pip3 install --upgrade pip
          pip3 install pandas
          pip3 install matplotlib
          pip3 install os
          pip3 install numpy

      - name: Execute script
        run: |
          python3 main.py
      
      - name: Debug
        run: |
          ls graphs

      #need to update the graph on push
      

      